### ISSUE TITLE
squid fails installing on SLE 15 SP2

### ISSUE THREAD

**Issue by Bischoff** [uyuni-project/sumaform#693] opened 2020-03-23 13:55 UTC
```
module.cucumber_testsuite.module.pxy.module.proxy.module.host.null_resource.provisioning[0] (remote-exec):
 ID: squid-configuration-dns-multicast
module.cucumber_testsuite.module.pxy.module.proxy.module.host.null_resource.provisioning[0] (remote-exec):
 Function: file.replace
module.cucumber_testsuite.module.pxy.module.proxy.module.host.null_resource.provisioning[0] (remote-exec):
 Name: /usr/share/doc/proxy/conf-template/squid.conf
module.cucumber_testsuite.module.pxy.module.proxy.module.host.null_resource.provisioning[0] (remote-exec):
 Result: False
module.cucumber_testsuite.module.pxy.module.proxy.module.host.null_resource.provisioning[0] (remote-exec):
 Comment: /usr/share/doc/proxy/conf-template/squid.conf: file not found
```

The problem is that file `/usr/share/doc/proxy/conf-template/squid.conf` is marked as a doc file, and on JeOS these files are removed automatically. Ping @admd .

(SP2 has other problems to install, but you can work around them by issuing this command inside the VM: `systemctl status qemu-ga@virtio\\x2dports-org.qemu.guest_agent.0`)

**Comment by admd** [comment] 2020-03-23 14:12
> The problem is that file `/usr/share/doc/proxy/conf-template/squid.conf` is marked as a doc file, and on JeOS these files are removed automatically. Ping @admd .
> 
I remember we had some similar problem in the past which was fixed by @juliogonzalez , I can't remember completely but it was about jabberd.

**Comment by juliogonzalez** [comment] 2020-03-23 14:22
Yes. @mantel fixed it with a PR this morning: https://github.com/uyuni-project/sumaform/pull/692

**Comment by juliogonzalez** [comment] 2020-03-23 14:23
He's fixing sumaform now, as for some reason it touches the template and no the installed file (which FMPOV is incorrect, but maybe will be corrected later).

**Comment by juliogonzalez** [comment] 2020-03-23 14:23
Please test Hubert's fix and close this issue if the problem is fixed.

**Comment by Bischoff** [comment] 2020-03-23 14:44
git pull should be enough Julio ?

**Closed** 2020-03-23 15:05 UTC
Labels: bug
